name: Deploy Frontend to Heroku

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy to Heroku
        run: |
          heroku git:remote --app automatedgrading-frontend
          git subtree push --prefix frontend heroku main
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
