# Generated by Django 5.1.7 on 2025-04-09 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grading',
            name='plagiarism_check',
        ),
        migrations.RemoveField(
            model_name='grading',
            name='plagiarism_report',
        ),
        migrations.RemoveField(
            model_name='grading',
            name='plagiarism_score',
        ),
    ]
