# Generated by Django 5.1.7 on 2025-04-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_alter_grading_student_alter_examsubmission_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grading',
            name='review_requested',
            field=models.BooleanField(default=False),
        ),
    ]
