# Generated by Django 5.1.7 on 2025-04-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_customuser_courses_enrolled_alter_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='courses_enrolled',
        ),
    ]
