# Generated by Django 5.1.7 on 2025-04-09 05:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_remove_grading_plagiarism_check_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlagiarismCheckReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('is_flagged', models.BooleanField(default=False)),
                ('checked_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('compared_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compared_to_checks', to='grading.examsubmission')),
                ('source_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_checks', to='grading.examsubmission')),
            ],
            options={
                'unique_together': {('source_submission', 'compared_submission')},
            },
        ),
    ]
