# Generated by Django 5.1.7 on 2025-04-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_grading_review_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='grading',
            name='reviewed_by_educator',
            field=models.BooleanField(default=False),
        ),
    ]
