# Generated by Django 5.1.7 on 2025-04-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_grading_reviewed_by_educator'),
    ]

    operations = [
        migrations.AddField(
            model_name='grading',
            name='initial_grade_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_file',
            field=models.FileField(blank=True, null=True, upload_to='media/exams/'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/submissions/'),
        ),
        migrations.AlterField(
            model_name='markingguide',
            name='marking_guide_file',
            field=models.FileField(blank=True, null=True, upload_to='media/marking_guides/'),
        ),
    ]
