# Generated by Django 5.1.7 on 2025-04-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_grading_initial_grade_score_alter_exam_exam_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='markingguide',
            name='grading_type',
            field=models.CharField(choices=[('fair', 'Fair Grading'), ('lenient', 'Lenient Grading'), ('strict', 'Strict Grading')], default='fair', max_length=10),
        ),
    ]
