name: Deploy Backend to Heroku

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Add Heroku git remote
        run: heroku git:remote --app automatedgrading-backend
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Push backend folder to Heroku
        run: |
          git config --global user.email "atongkurabraham@gmail.com"
          git config --global user.name "Atong Abraham Kur"
          git subtree push --prefix backend https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/automatedgrading-backend.git main
