name: Deploy Backend to Heroku

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy to Heroku
        run: |
          echo "Logging in to Heroku..."
          echo "$HEROKU_API_KEY" | heroku auth:token
          heroku git:remote --app automatedgrading-backend
          git subtree push --prefix backend heroku main
        env:
          HEROKU_API_KEY: "HRKU-46d9f635-d5a3-4d6b-a5f7-d9ad45dd3572"
          HEROKU_USERNAME: "atongkurabraham@gmail.com"
          HEROKU_PASSWORD: "atongkurabraham@gmail.com"
